name: .NET Console App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore TestApp2/TestApp2.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore TestApp2/TestApp2.csproj
      
    - name: Run console app
      run: dotnet run --project TestApp2/TestApp2.csproj
